### ISSUE TITLE
Doesnt install on Raspberry Pi

### ISSUE THREAD

**Issue by tgwaste** [najnesnaj/pinetime-zephyr#7]
During:
pip3 install --user -r ~/zephyrproject/zephyr/scripts/requirements.txt

There were lots of errors with regard to **No package 'libffi' found**
So I installed: **apt-get -y install python-cffi libffi-dev**

```
Now The error is:

    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:
```

Would be awesome if this worked on Pi.

**Comment by SuperPrower** [comment]
I think this issue would be more appropriate at the [Zephyr bugtracker](https://github.com/zephyrproject-rtos/zephyr/)?

**Comment by najnesnaj** [comment]
In this repo is just code, which should compile on any platform zephyr compiles on.

**Comment by tgwaste** [comment]
Moved, thanks
